name: Daily Auto Commit

on:
  workflow_dispatch:
  

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Configure Git
        run: |
          git config user.name 'Andrian17'
          git config user.email 'andriancimen123@gmail.com'
      
      # - name: Create Commit
      #   run: |
      #     git add .
      #     git commit -m "Daily auto commit by bot"

      - name: Create Commit
        run: |
          chmod +x ./job.sh
          ./job.sh
      
      - name: Push Changes
        run: git push
